print(" Calculateur de paiement")
bill_total_str = input("Montant total de la facture (€) : ")
bill_total = float(bill_total_str)
tip_percentage_str = input("Pourcentage de pourboire (%) : ")
tip_percentage = int(tip_percentage_str)
num_people_str = input("Nombre de personnes : ")
num_people = int(num_people_str)
tip_amount = bill_total * (tip_percentage / 100)
total_with_tip = bill_total + tip_amount
amount_per_person = total_with_tip / num_people
final_amount_per_person = round(amount_per_person, 2)
print("\n Resumer de paiement ")
print(f"Total avec pourboire : {total_with_tip:.2f} €")
print(f"Chaque personne doit payer : {final_amount_per_person:.2f} €")
print(f"(Basé sur une facture de {bill_total:.2f} € avec {tip_percentage}% de pourboire, partagé entre {num_people} personnes.)")
